# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Erik J. Olson
description: >- # this means to ignore newlines until "baseurl:"
  The impossible just takes longer.
favicon: /assets/img/logo.png
apple_touch_icon: /assets/img/logo.png
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
cover: true
no_drawer: false

# Build settings
markdown: kramdown
remote_theme: hydecorp/hydejack
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

menu:
  - title: Home
    url: /
  - title: Posts
    url: /posts/
  - title: About
    url: /about/

rss: true

author:
  name: Erik J. Olson
  email: hello@erikjolson.com
  picture: /assets/img/me.jpg
  about: |
    test test test
  social:
    github: arychj
    resume: https://arychj.github.io
    qrz: K7NCC
    contact: /contact
    rss: https://new.erikjolson.com/feed.xml

date_format: "%Y-%m-%d"

accent_image: /assets/img/sidebar-bg.jpg

hydejack:
  dark_mode:
    dynamic: false
    icon:    false
    always:  true

kramdown:
  math_engine: mathjax
  math_engine_opts: {}

collections:
  featured_categories:
    permalink:         /:name/
    output:            true
  featured_tags:
    permalink:         /tag-:name/
    output:            true

